tag_index:
  path: /api/v1/tags
  controller: App\Controller\TagController::index
  methods: [GET]

tag_post:
  path: /api/v1/tags
  controller: App\Controller\TagController::create
  methods: [POST]
